version: '3'

volumes:
  sqlite_data:

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - BACKEND_PORT=8000
      - url=test.localhost.com:3000
    ports:
      - "3000:3000"
    volumes:
      - "sqlite_data:/app/resources"

